### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by liguopeng0923** [TencentARC/ST-LLM#18]
Hi, 

I run the scripts/inference/vcgbench/test_general.sh following your ReadMe. But I get the following error which is difficult to be solved for me.

Traceback (most recent call last):
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/test/vcgbench/videochatgpt_benchmark_general.py", line 127, in <module>
    run_inference(args)
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/test/vcgbench/videochatgpt_benchmark_general.py", line 109, in run_inference
    llm_message = chat.answer(conv=chat_state,
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/conversation/conversation.py", line 231, in answer
    outputs = llama_model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1609, in generate
    result = self._beam_search(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 3062, in _beam_search
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/models/st_llm.py", line 119, in forward
    return super(STLLMForCausalLM, self).forward(inputs_embeds=inputs_embeds, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1196, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/models/st_llm.py", line 58, in forward
    return super(STLLMLlamaModel, self).forward(inputs_embeds=inputs_embeds, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 990, in forward
    causal_mask = self._update_causal_mask(attention_mask, inputs_embeds, cache_position)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1071, in _update_causal_mask
    attention_mask.shape[-1] if isinstance(attention_mask, torch.Tensor) else cache_position[-1] + 1
IndexError: index -1 is out of bounds for dimension 0 with size 0

**Comment by farewellthree** [comment]
Sorry, I haven't encountered this bug before. Could you trace why the attention_mask is empty?

**Comment by liguopeng0923** [comment]
Hi，

I think this is because you dont transport it in this following function (L234 in ST-LLM/stllm/conversation/conversation.py). But I meet new problems (the shape of attention mask is not normal) when I try to transport it. 
<img width="675" alt="image" src="https://github.com/TencentARC/ST-LLM/assets/61257834/c0759395-fda3-4b68-a968-e67faa3ebca1">

**Comment by liguopeng0923** [comment]
The following error ocurrs when I fix the L234 in ST-LLM/stllm/conversation/conversation.py.

Traceback (most recent call last):
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/test/vcgbench/videochatgpt_benchmark_general.py", line 127, in <module>
    run_inference(args)
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/test/vcgbench/videochatgpt_benchmark_general.py", line 109, in run_inference
    llm_message = chat.answer(conv=chat_state,
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/conversation/conversation.py", line 231, in answer
    outputs = llama_model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1609, in generate
    result = self._beam_search(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 3062, in _beam_search
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/models/st_llm.py", line 119, in forward
    return super(STLLMForCausalLM, self).forward(inputs_embeds=inputs_embeds, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1196, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt_alipayshnas/zirui.lgp/ST-LLM/stllm/models/st_llm.py", line 58, in forward
    return super(STLLMLlamaModel, self).forward(inputs_embeds=inputs_embeds, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 990, in forward
    causal_mask = self._update_causal_mask(attention_mask, inputs_embeds, cache_position)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1077, in _update_causal_mask
    causal_mask *= torch.arange(target_length, device=device) > cache_position.reshape(-1, 1)
RuntimeError: The size of tensor a (586) must match the size of tensor b (0) at non-singleton dimension 0

**Comment by liguopeng0923** [comment]
Hi,

Can we chat this problem in WeChat for more efficient discussions? My WeChat is "CodeFighting".
